"use client";
import { useState, useTransition } from "react";
import type { PlatformUserSearchResponse } from "@housepoints/contracts";
import { searchPlatformUsers } from "@/app/actions/platform";

export function PlatformUserSearch() {
  const [query, setQuery] = useState(""); const [users, setUsers] = useState<PlatformUserSearchResponse["users"]>([]); const [message, setMessage] = useState<string | null>(null); const [searched, setSearched] = useState(false); const [pending, startTransition] = useTransition();
  function search() { if (query.trim().length < 2) { setMessage("Enter at least two characters."); return; } startTransition(async () => { const result = await searchPlatformUsers(query.trim()); setSearched(true); if (!result.ok) { setMessage(result.message); setUsers([]); return; } setMessage(null); setUsers(result.data.users); }); }
  return <section className="space-y-4"><form className="flex gap-3" onSubmit={(event) => { event.preventDefault(); search(); }}><label className="sr-only" htmlFor="platform-user-query">Search users</label><input id="platform-user-query" className="min-w-0 flex-1 rounded-lg border bg-background px-3 py-2" placeholder="Name, email, or Auth0 subject" value={query} onChange={(event) => setQuery(event.target.value)} /><button className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground disabled:opacity-50" disabled={pending} type="submit">{pending ? "Searching…" : "Search"}</button></form>{message ? <p role="alert" className="text-sm text-destructive">{message}</p> : null}{searched && !message && users.length === 0 ? <p className="rounded-2xl border bg-card p-5 text-sm text-muted-foreground">No matching users.</p> : null}<div className="space-y-4">{users.map((user) => <article key={user.id} className="rounded-2xl border bg-card p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-display text-xl font-semibold">{user.displayName}</h2><p className="text-sm text-muted-foreground">{user.email ?? "No email"}</p><p className="mt-1 font-mono text-xs text-muted-foreground">{user.auth0Sub}</p></div><div className="text-right text-sm"><p>{user.activeDeviceCount} active device{user.activeDeviceCount === 1 ? "" : "s"}</p>{user.deletionRequestedAt ? <p className="font-semibold text-destructive">Deletion requested</p> : null}</div></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-b text-xs uppercase text-muted-foreground"><tr><th className="py-2">Organization</th><th>Role</th><th>Membership</th><th>Organization</th><th>Effective access</th><th>Capabilities</th></tr></thead><tbody>{user.memberships.map((membership) => <tr key={membership.organizationId} className="border-b last:border-0"><td className="py-3"><p className="font-semibold">{membership.organizationName}</p><p className="text-xs text-muted-foreground">{membership.organizationSlug}</p></td><td>{membership.role}</td><td>{membership.membershipStatus}</td><td>{membership.organizationStatus}</td><td>{membership.effectiveAccess}</td><td className="text-xs">{membership.capabilities.join(", ") || "None"}</td></tr>)}</tbody></table>{user.memberships.length === 0 ? <p className="py-3 text-sm text-muted-foreground">No memberships.</p> : null}</div></article>)}</div></section>;
}
