"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import type { PlatformSupportCaseDetail as SupportCase } from "@housepoints/contracts";
import { toast } from "sonner";
import { addPlatformSupportNote, updatePlatformSupportCase } from "@/app/actions/platform";

export function PlatformSupportCaseDetail({ supportCase }: { supportCase: SupportCase }) {
  const router = useRouter();
  const [status, setStatus] = useState(supportCase.status); const [priority, setPriority] = useState(supportCase.priority);
  const [note, setNote] = useState(""); const [pending, startTransition] = useTransition();
  function save() { startTransition(async () => { const result = await updatePlatformSupportCase({ supportCaseId: supportCase.id, status, priority }); if (!result.ok) { toast.error(result.message); return; } toast.success("Support case updated."); router.refresh(); }); }
  function addNote() { startTransition(async () => { const result = await addPlatformSupportNote({ supportCaseId: supportCase.id, body: note }); if (!result.ok) { toast.error(result.message); return; } toast.success("Private note added."); setNote(""); router.refresh(); }); }
  return <div className="space-y-6">
    <section className="rounded-2xl border bg-card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="font-display text-3xl font-bold">{supportCase.title}</h1><p className="mt-2 max-w-3xl whitespace-pre-wrap text-sm text-muted-foreground">{supportCase.summary}</p></div><p className="text-xs text-muted-foreground">Opened {new Date(supportCase.createdAt).toLocaleString()}</p></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><p className="text-sm"><span className="font-semibold">Organization:</span> {supportCase.organization?.name ?? "Not linked"}</p><p className="text-sm"><span className="font-semibold">User:</span> {supportCase.user?.displayName ?? "Not linked"}</p></div><div className="mt-4 flex flex-wrap items-end gap-3"><label className="text-sm font-medium">Status<select aria-label="Case status" className="mt-1 block rounded-lg border bg-background px-3 py-2" value={status} onChange={(event) => setStatus(event.target.value as typeof status)}><option value="OPEN">Open</option><option value="IN_PROGRESS">In progress</option><option value="RESOLVED">Resolved</option></select></label><label className="text-sm font-medium">Priority<select aria-label="Case priority" className="mt-1 block rounded-lg border bg-background px-3 py-2" value={priority} onChange={(event) => setPriority(event.target.value as typeof priority)}><option value="LOW">Low</option><option value="NORMAL">Normal</option><option value="HIGH">High</option><option value="URGENT">Urgent</option></select></label><button className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground disabled:opacity-50" disabled={pending || (status === supportCase.status && priority === supportCase.priority)} onClick={save}>Save case</button></div></section>
    <section className="rounded-2xl border bg-card p-5"><h2 className="font-display text-xl font-semibold">Private operator notes</h2><p className="mt-1 text-sm text-muted-foreground">Append-only notes are restricted to platform operators. Their contents are not copied into the general audit trail.</p><div className="mt-4 space-y-3">{supportCase.notes.map((entry) => <article key={entry.id} className="rounded-xl border p-3"><p className="whitespace-pre-wrap text-sm">{entry.body}</p><p className="mt-2 text-xs text-muted-foreground">{entry.authorAuth0Sub} · {new Date(entry.createdAt).toLocaleString()}</p></article>)}{supportCase.notes.length === 0 ? <p className="text-sm text-muted-foreground">No notes yet.</p> : null}</div><label className="mt-4 block text-sm font-medium">Add private note<textarea aria-label="Private support note" className="mt-1 block min-h-28 w-full rounded-lg border bg-background px-3 py-2" maxLength={2000} value={note} onChange={(event) => setNote(event.target.value)} /></label><button className="mt-3 rounded-lg border px-4 py-2 text-sm font-semibold disabled:opacity-50" disabled={pending || note.trim().length < 3} onClick={addNote}>Add private note</button></section>
  </div>;
}
