-- CreateEnum
CREATE TYPE "Trait" AS ENUM (
  'LEADERSHIP',
  'OWNERSHIP',
  'COLLABORATION',
  'MENTORSHIP',
  'TECHNICAL_EXCELLENCE',
  'PROBLEM_SOLVING',
  'INNOVATION',
  'KNOWLEDGE_SHARING',
  'COMMUNICATION',
  'CUSTOMER_FOCUS',
  'RELIABILITY',
  'INITIATIVE',
  'PROCESS_IMPROVEMENT',
  'TEAM_SUPPORT',
  'ACCOUNTABILITY',
  'ADAPTABILITY',
  'POSITIVE_INFLUENCE',
  'ABOVE_AND_BEYOND',
  'CULTURE_CHAMPION',
  'UNSUNG_HERO'
);

-- AlterTable
ALTER TABLE "PointTransaction" ADD COLUMN "trait" "Trait";
