ALTER TYPE "AuditEventType" ADD VALUE 'MODERATION_WARNING_ISSUED';
ALTER TYPE "AuditEventType" ADD VALUE 'MEMBER_SUSPENDED';
ALTER TYPE "AuditEventType" ADD VALUE 'MEMBER_RESTORED';
ALTER TYPE "NotificationType" ADD VALUE 'MODERATION_WARNING';

ALTER TABLE "OrganizationMembership"
ADD COLUMN "suspendedAt" TIMESTAMP(3),
ADD COLUMN "suspensionReason" TEXT,
ADD COLUMN "suspendedByAuth0Sub" TEXT;
