import { useState } from "react";
import { Modal, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { ACTIVITY_REPORT_OPTIONS, type ReportCategory } from "@/lib/moderation-report";


export function ReportActivityModal({ visible, pending, onClose, onSubmit }: { visible: boolean; pending: boolean; onClose: () => void; onSubmit: (category: ReportCategory, details: string) => void }) {
  const [category, setCategory] = useState<ReportCategory>("INAPPROPRIATE_CONTENT");
  const [details, setDetails] = useState("");
  return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={styles.backdrop}><View style={styles.card}><Text style={styles.title}>Report this activity</Text><Text style={styles.body}>A platform operator will review the saved activity snapshot.</Text><View style={styles.options}>{ACTIVITY_REPORT_OPTIONS.map((option) => <Pressable key={option.value} onPress={() => setCategory(option.value)} style={[styles.option, category === option.value && styles.optionSelected]}><Text style={[styles.optionText, category === option.value && styles.optionTextSelected]}>{option.label}</Text></Pressable>)}</View><TextInput value={details} onChangeText={setDetails} placeholder="Details (optional)" multiline maxLength={1000} style={styles.input} /><View style={styles.actions}><Pressable onPress={onClose} style={styles.cancel}><Text style={styles.cancelText}>Cancel</Text></Pressable><Pressable disabled={pending} onPress={() => onSubmit(category, details.trim())} style={styles.submit}><Text style={styles.submitText}>{pending ? "Submitting…" : "Submit report"}</Text></Pressable></View></View></View></Modal>;
}
const styles = StyleSheet.create({ backdrop: { flex: 1, backgroundColor: "rgba(15,23,42,0.55)", justifyContent: "center", padding: 20 }, card: { backgroundColor: "#fff", borderRadius: 16, padding: 20 }, title: { fontSize: 20, fontWeight: "700", color: "#0f172a" }, body: { marginTop: 6, color: "#64748b" }, options: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 16 }, option: { borderWidth: 1, borderColor: "#cbd5e1", borderRadius: 999, paddingHorizontal: 12, paddingVertical: 8 }, optionSelected: { backgroundColor: "#dbeafe", borderColor: "#2563eb" }, optionText: { color: "#475569", fontWeight: "600" }, optionTextSelected: { color: "#1d4ed8" }, input: { minHeight: 96, marginTop: 16, borderWidth: 1, borderColor: "#cbd5e1", borderRadius: 10, padding: 12, textAlignVertical: "top" }, actions: { flexDirection: "row", justifyContent: "flex-end", gap: 10, marginTop: 16 }, cancel: { padding: 10 }, cancelText: { fontWeight: "700", color: "#475569" }, submit: { backgroundColor: "#2563eb", borderRadius: 9, paddingHorizontal: 14, paddingVertical: 10 }, submitText: { color: "#fff", fontWeight: "700" } });
