import Link from "next/link";
import { readPlatformModerationReports } from "@/app/actions/platform";

export const dynamic = "force-dynamic";

export default async function PlatformModerationPage() {
  const data = await readPlatformModerationReports();
  return <main className="min-h-screen bg-background px-4 py-8"><div className="mx-auto max-w-5xl space-y-6"><Link href="/platform" className="text-sm font-semibold text-primary hover:underline">← Support dashboard</Link><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">Trust and safety</p><h1 className="mt-2 font-display text-3xl font-bold">Moderation reports</h1><p className="mt-2 text-sm text-muted-foreground">Immutable evidence snapshots preserve what was reported even if the underlying activity or membership later changes.</p></div><div className="space-y-4">{data.reports.map((report) => <article key={report.id} className="rounded-2xl border bg-card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-display text-xl font-semibold">{report.targetType.replaceAll("_", " ")}</h2><p className="text-sm text-muted-foreground">{report.organization.name} · Reported by {report.reporter.displayName}</p></div><div className="text-right text-xs font-semibold"><p>{report.category} · {report.status}</p><p className="mt-1 text-muted-foreground">{report.priorReportCount} prior report{report.priorReportCount === 1 ? "" : "s"}</p></div></div>{report.details ? <p className="mt-3 whitespace-pre-wrap text-sm">{report.details}</p> : null}<details className="mt-3 rounded-xl border p-3"><summary className="cursor-pointer text-sm font-semibold">Evidence snapshot</summary><pre className="mt-3 overflow-x-auto whitespace-pre-wrap text-xs text-muted-foreground">{JSON.stringify(report.evidenceSnapshot, null, 2)}</pre></details><p className="mt-3 text-xs text-muted-foreground">Submitted {new Date(report.createdAt).toLocaleString()} · Target {report.targetId}</p></article>)}{data.reports.length === 0 ? <p className="rounded-2xl border bg-card p-5 text-sm text-muted-foreground">No reports have been submitted.</p> : null}</div></div></main>;
}
